#!/bin/bash

sudo yum update -y
sudo yum install docker -y

sudo service iptables start
sudo iptables -L

sudo iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

sudo iptables -A INPUT -p tcp --dport 2377 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 4789 -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 7946 -j ACCEPT
sudo iptables -I INPUT 9 -p udp --dport 4789 -j ACCEPT
sudo iptables -I INPUT 8 -p udp --dport 7946 -j ACCEPT

sudo iptables -P INPUT DROP

service iptables save

sudo service iptables restart
sudo service docker start
sudo chkconfig docker
sudo chkconfig iptables
